[package]
name = "rs-webmark"
version = "0.1.0"
authors = ["alexandrel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maud = "*"
pulldown-cmark = "*"
syntect = "3.0"